---
- name: apt update
  apt:
    update_cache: yes
- name: Install haproxy
  apt:
    name: haproxy
    state: present
- name: configure haproxy
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
- name: restart haproxy
  service:
    name: haproxy
    state: restarted
- name: Install nginx
  apt:
    name: nginx
    state: present
- name: configure nginx for udp
  template: 
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf
- name: configure nginx for udp
  template:
    src: templates/default.conf
    dest: /etc/nginx/sites-available/default
- name: restart nginx
  service:
    name: nginx
    state: restarted
- name: install SNMPd for testing
  apt: 
    name: snmp
    state: present   